-- Run this in the Supabase SQL Editor once, then fill in the env vars in .env
-- Tables mirror the SQLite schema so the app works on either backend.

create extension if not exists "pgcrypto";

create table if not exists users (
  id            bigint generated by default as identity primary key,
  first_name    text not null,
  last_name     text not null,
  email         text unique,
  mobile        text unique,
  password_hash text not null,
  verified      boolean not null default false,
  created_at    timestamptz not null default now()
);

create table if not exists otps (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references users(id) on delete cascade,
  code_hash  text not null,
  channel    text not null check (channel in ('email', 'sms')),
  expires_at timestamptz not null,
  used       boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists otps_user_channel_idx on otps (user_id, channel, used, expires_at desc);

create table if not exists login_attempts (
  email_or_mobile text primary key,
  count           integer not null default 0,
  locked_until    timestamptz
);

-- Row Level Security: allow the API keys (publishable/secret) full access.
-- The publishable key maps to a restricted role, so these policies make it usable.
-- NOTE (dev): open policies. In production with a real SECRET key, you can drop these
-- or tighten them since the service role bypasses RLS anyway.
alter table users enable row level security;
create policy "app_all_users" on users for all using (true) with check (true);

alter table otps enable row level security;
create policy "app_all_otps" on otps for all using (true) with check (true);

alter table login_attempts enable row level security;
create policy "app_all_login_attempts" on login_attempts for all using (true) with check (true);