-- Run this in the Supabase SQL Editor once (idempotent; safe to re-run).
-- Tables mirror the SQLite schema so the app works on either backend.
-- RLS is hardened: ONLY the service_role (the app's secret/service-role key)
-- can access the tables. The publishable/anon key is blocked from direct access.
-- You can still manage rows freely in the Supabase Table Editor (it uses the
-- admin role, which bypasses RLS).

create extension if not exists "pgcrypto";

create table if not exists users (
  id            bigint generated by default as identity primary key,
  first_name    text not null,
  last_name     text not null,
  email         text unique,
  mobile        text unique,
  password_hash text not null,
  verified      boolean not null default false,
  verified_at   timestamptz,
  last_login_at timestamptz,
  created_at    timestamptz not null default now()
);

create table if not exists otps (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references users(id) on delete cascade,
  code_hash  text not null,
  channel    text not null check (channel in ('email', 'sms')),
  expires_at timestamptz not null,
  used       boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists otps_user_channel_idx on otps (user_id, channel, used, expires_at desc);

create table if not exists login_attempts (
  email_or_mobile text primary key,
  count           integer not null default 0,
  locked_until    timestamptz
);

create table if not exists logins (
  id        bigint generated by default as identity primary key,
  user_id   bigint not null references users(id) on delete cascade,
  login_at  timestamptz not null default now()
);
create index if not exists logins_user_idx on logins (user_id, id desc);

-- Add new columns to existing tables (safe to re-run)
alter table users add column if not exists verified_at timestamptz;
alter table users add column if not exists last_login_at timestamptz;

-- Remove any previously created open policies (dev convenience from earlier)
drop policy if exists app_all_users on users;
drop policy if exists app_all_otps on otps;
drop policy if exists app_all_login_attempts on login_attempts;
drop policy if exists app_all_logins on logins;

-- Enable RLS on every table
alter table users enable row level security;
alter table otps enable row level security;
alter table login_attempts enable row level security;
alter table logins enable row level security;

-- Allow ONLY the service_role (the app's secret/service-role key) full access.
-- service_role bypasses RLS by design, so the app keeps working;
-- the publishable/anon key now gets denied on direct table access.
create policy "service_role_all_users" on users
  for all to service_role using (true) with check (true);
create policy "service_role_all_otps" on otps
  for all to service_role using (true) with check (true);
create policy "service_role_all_login_attempts" on login_attempts
  for all to service_role using (true) with check (true);
create policy "service_role_all_logins" on logins
  for all to service_role using (true) with check (true);
